### ISSUE TITLE
Metallurgy fluids killing cows

### ISSUE THREAD

**Issue by Maleia** [TheRoBrit/Moo-Fluids#17]
When milking cows that have metallurgy fluids to them, it spills the liquid on the ground and the cows burn to death from it.  

(I am not the same person as Wuweird that posted on the forums, meaning at least a 2nd person is encountering the issue.)

**Comment by TheRoBrit** [comment]
Which version of the mod are you encountering this issue with? As the most recent versions shouldn't have this issue.

**Comment by Maleia** [comment]
I am using version 1.5.01.19a

**Comment by mtrevor** [comment]
I *am* wuweird from the forums, and I'm also using version 1.5.01.19a. After a bit of experimentation, it seems like the fluid drop _only_ happens if you're using a single bucket. If you milk a fluid cow while holding a stack of buckets, the fluid is collected as expected.

This isn't limited to Metallurgy fluids, either, it seems consistent with all fluid cows. I've replicated this on molten gold (Minecraft), energized glowstone (TE), and tannin (MineChem) cows.
